"""Transparent local research-priority heuristic."""
from intelligence_director.enums import PriorityBand
from intelligence_director.models import IntelligenceSignal,ResearchCandidate,ResearchPriorityScore
WEIGHTS={"strategic_relevance":.12,"audience_relevance":.10,"reach_potential":.05,"revenue_compatibility":.05,"urgency":.10,"freshness_risk":.08,"evidence_gap":.10,"contradiction_severity":.10,"competitor_importance":.05,"content_opportunity_strength":.05,"production_usefulness":.05,"verification_cost":-.07,"expected_research_value":.08,"shelf_life":.04,"founder_priority":.08,"safety_compliance_risk":.12}
def score_priority(candidate:ResearchCandidate,signal:IntelligenceSignal,**overrides:float)->ResearchPriorityScore:
    d={"strategic_relevance":signal.context.business_relevance,"audience_relevance":signal.context.audience_relevance,"reach_potential":50,"revenue_compatibility":50,"urgency":signal.context.urgency,"freshness_risk":100-signal.freshness_window_hours/87.6,"evidence_gap":100*(1-signal.confidence),"contradiction_severity":overrides.get("contradiction_severity",0),"competitor_importance":overrides.get("competitor_importance",0),"content_opportunity_strength":60 if signal.context.content_opportunity_id else 30,"production_usefulness":60,"verification_cost":candidate.verification_cost,"expected_research_value":70,"shelf_life":min(100,signal.freshness_window_hours/87.6),"founder_priority":overrides.get("founder_priority",0),"safety_compliance_risk":overrides.get("safety_compliance_risk",0)}
    d.update({k:v for k,v in overrides.items() if k in d}); c={k:round(d[k]*w,2) for k,w in WEIGHTS.items()}; score=max(0,min(100,round(sum(c.values())+25-(15 if candidate.duplicate_topic else 0),2)))
    band=PriorityBand.NOW if score>=70 else PriorityBand.SOON if score>=55 else PriorityBand.MONITOR if score>=35 else PriorityBand.ARCHIVE if score>=20 else PriorityBand.REJECT
    return ResearchPriorityScore(candidate_id=candidate.candidate_id,dimensions=d,weighted_contributions=c,overall=score,band=band,rationale=["Deterministic weighted heuristic","Research cost and duplicate topics reduce priority"])
