"""Knowledge Manager vocabulary."""
from enum import StrEnum
class KnowledgeCategory(StrEnum):
    VERIFIED_FACT="verified_fact"; QUALIFIED_FACT="qualified_fact"; PRODUCT_CAPABILITY="product_capability"; PRODUCT_AVAILABILITY="product_availability"; PRICING="pricing_or_plan"; API_BEHAVIOR="API_behavior"; PROVIDER_RELIABILITY="provider_reliability"; PLATFORM_POLICY="platform_policy"; COMPETITOR_POSITIONING="competitor_positioning"; AUDIENCE_INSIGHT="audience_insight"; CONTENT_PERFORMANCE="content_performance"; PRODUCTION_LESSON="production_lesson"; ENGINEERING_DECISION="engineering_decision"; FOUNDER_DECISION="founder_decision"; WORKFLOW_PATTERN="workflow_pattern"; CONTENT_OPPORTUNITY="content_opportunity"; TUTORIAL="tutorial_knowledge"; HISTORICAL="historical_record"; UNVERIFIED="unverified_observation"; PRIVATE="prohibited_private_data"
class EvidenceClass(StrEnum): OFFICIAL="official"; FIRST_PARTY="first_party"; CORROBORATED="corroborated"; FOUNDER="founder_verified"; INTERNAL="internal_artifact"; COMMUNITY="community_signal"
class ApprovalStatus(StrEnum): PENDING="pending"; APPROVED="approved"; REJECTED="rejected"
class FounderDecision(StrEnum): APPROVE="approve_store"; SIGNAL="approve_as_unverified_signal"; EVIDENCE="request_more_evidence"; PRIVATE="reject_private_or_sensitive"; LOW_VALUE="reject_low_value"; ARCHIVE="archive"; SUPERSEDE="supersede"; WITHDRAW="withdraw"
class ConflictStatus(StrEnum): NONE="none"; PENDING="pending_review"; MINOR="minor_context_difference"; REGION="region_specific"; VERSION="time_version_conflict"; MATERIAL="material_conflict"; CORRECTED="corrected"; UNRESOLVED="unresolved"; WITHDRAWN="withdrawn"
class FreshnessStatus(StrEnum): FRESH="fresh"; DUE="refresh_due"; STALE="stale"; EXPIRED="expired"; SUPERSEDED="superseded"; ARCHIVED="archived"; VERIFY="verification_required"; TIMELESS="timeless_with_review"
class RetentionAction(StrEnum): DISCARD="discard_after_run"; TEMPORARY="retain_temporarily"; EXPIRY="retain_until_expiry"; VERIFIED="retain_as_verified_knowledge"; HISTORICAL="retain_as_historical_record"; FOUNDER="founder_review_required"; PROHIBITED="prohibited_from_storage"
class DuplicateKind(StrEnum): EXACT="exact_duplicate"; EQUIVALENT="equivalent_claim"; PARTIAL="partial_overlap"; VERSION="new_version"; CONTRADICTION="contradiction"; UNRELATED="unrelated_information"
class SourceSystem(StrEnum): INTELLIGENCE_DIRECTOR="intelligence_director"; WEB_INTELLIGENCE="web_intelligence"; TREND_INTELLIGENCE="trend_intelligence"; PRODUCTION_RESEARCH="production_research"; MISSION_ARTIFACT="mission_artifact"; CREATIVE_QUALITY="creative_quality"; FOUNDER_NOTE="founder_verified_note"; OWNED_ANALYTICS="owned_analytics"; FIXTURE="deterministic_fixture"
